
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      timeout: 3000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=UTC
    username: app_user
    password: mysql2025


server:
  host: 0.0.0.0
  port: 8080

